name: Build to gh-pages

on:
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm

      - name: Install Dependencies
        run: npm install

      - name: Build Application
        run: npm run build --omit=dev --base-href=/burger-intensive_angular/

      - name: Commit to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.MY_GITHUB_TOKEN }}
          publish_dir: ./dist/burger-intensive_angular/
